platform :ios, '6.0'
pod 'AFNetworking', '~> 2.0.3'
pod 'Facebook-iOS-SDK', '~> 3.11.0'
#pod 'JHSidebar', '~> 0.1.0'
pod 'JHSidebar', :path => '../JHSidebar/JHSidebar.podspec'
pod 'JSONAPI', '~> 0.1.0'
pod 'Raven', '~> 0.3.0'
pod 'STTwitter', '~> 0.0.7'
