//
//  SHStyleKit.m
//  SpotHopper
//
//  Created by SpotHopper on 5/14/14.
//  Copyright (c) 2014 SpotHopper. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "SHStyleKit.h"


@implementation SHStyleKit

#pragma mark Cache

static UIColor* _myTintColor = nil;
static UIColor* _myTintColorTransparent = nil;
static UIColor* _myTextColor = nil;
static UIColor* _myWhiteColor = nil;
static UIColor* _myLightHeaderColor = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _myTintColor = [UIColor colorWithRed: 0.878 green: 0.4 blue: 0.149 alpha: 1];
    _myTintColorTransparent = [SHStyleKit.myTintColor colorWithAlphaComponent: 0.8];
    _myTextColor = [UIColor colorWithRed: 0.4 green: 0.4 blue: 0.4 alpha: 1];
    _myWhiteColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    _myLightHeaderColor = [UIColor colorWithRed: 0.992 green: 0.969 blue: 0.945 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)myTintColor { return _myTintColor; }
+ (UIColor*)myTintColorTransparent { return _myTintColorTransparent; }
+ (UIColor*)myTextColor { return _myTextColor; }
+ (UIColor*)myWhiteColor { return _myWhiteColor; }
+ (UIColor*)myLightHeaderColor { return _myLightHeaderColor; }

#pragma mark Drawing Methods

+ (void)drawWineIconWithColorName: (NSString*)colorName;
{

    //// Variable Declarations
    UIColor* namedColor = [colorName isEqualToString: @"myTintColor"] ? SHStyleKit.myTintColor : [colorName isEqualToString: @"myTintColorTransparent"] ? SHStyleKit.myTintColorTransparent : [colorName isEqualToString: @"myTextColor"] ? SHStyleKit.myTextColor : [colorName isEqualToString: @"myWhiteColor"] ? SHStyleKit.myWhiteColor : SHStyleKit.myTintColor;

    //// Bezier 2 Drawing
    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(285.6, 207.6)];
    [bezier2Path addLineToPoint: CGPointMake(759.6, 207.6)];
    bezier2Path.miterLimit = 4;

    [SHStyleKit.myTintColor setFill];
    [bezier2Path fill];


    //// Bezier 4 Drawing
    UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
    [bezier4Path moveToPoint: CGPointMake(732.5, 54.3)];
    [bezier4Path addLineToPoint: CGPointMake(297.5, 54.3)];
    [bezier4Path addCurveToPoint: CGPointMake(313.22, 194) controlPoint1: CGPointMake(300.58, 105.59) controlPoint2: CGPointMake(305.82, 152.16)];
    [bezier4Path addLineToPoint: CGPointMake(725.53, 194)];
    [bezier4Path addCurveToPoint: CGPointMake(732.5, 54.3) controlPoint1: CGPointMake(730.17, 152.11) controlPoint2: CGPointMake(732.5, 105.52)];
    [bezier4Path closePath];
    [bezier4Path moveToPoint: CGPointMake(722.11, 221.1)];
    [bezier4Path addLineToPoint: CGPointMake(318.45, 221.1)];
    [bezier4Path addCurveToPoint: CGPointMake(526.8, 468.8) controlPoint1: CGPointMake(352.48, 383.06) controlPoint2: CGPointMake(422.24, 466.18)];
    [bezier4Path addCurveToPoint: CGPointMake(641.2, 425.6) controlPoint1: CGPointMake(573.6, 469.8) controlPoint2: CGPointMake(611.1, 455.5)];
    [bezier4Path addCurveToPoint: CGPointMake(722.11, 221.1) controlPoint1: CGPointMake(681.42, 385.51) controlPoint2: CGPointMake(708.47, 317.02)];
    [bezier4Path closePath];
    [bezier4Path moveToPoint: CGPointMake(524, 920.7)];
    [bezier4Path addCurveToPoint: CGPointMake(471.3, 969.7) controlPoint1: CGPointMake(509.4, 939) controlPoint2: CGPointMake(491.8, 955.4)];
    [bezier4Path addLineToPoint: CGPointMake(572.9, 969.7)];
    [bezier4Path addCurveToPoint: CGPointMake(524, 920.7) controlPoint1: CGPointMake(553.2, 955.4) controlPoint2: CGPointMake(536.9, 939)];
    [bezier4Path closePath];
    [bezier4Path moveToPoint: CGPointMake(786.1, 0)];
    [bezier4Path addCurveToPoint: CGPointMake(786.5, 26.7) controlPoint1: CGPointMake(786.1, 0) controlPoint2: CGPointMake(786.5, 26.7)];
    [bezier4Path addCurveToPoint: CGPointMake(679.4, 464) controlPoint1: CGPointMake(789.8, 245.9) controlPoint2: CGPointMake(754.8, 388.9)];
    [bezier4Path addCurveToPoint: CGPointMake(553.3, 522.1) controlPoint1: CGPointMake(645.1, 498.1) controlPoint2: CGPointMake(602.8, 517.6)];
    [bezier4Path addLineToPoint: CGPointMake(553.3, 861.9)];
    [bezier4Path addCurveToPoint: CGPointMake(666.6, 958) controlPoint1: CGPointMake(570.3, 904.6) controlPoint2: CGPointMake(607.4, 936.1)];
    [bezier4Path addCurveToPoint: CGPointMake(688.4, 996) controlPoint1: CGPointMake(682.1, 963.8) controlPoint2: CGPointMake(691.3, 979.8)];
    [bezier4Path addCurveToPoint: CGPointMake(654.9, 1024) controlPoint1: CGPointMake(685.5, 1012.2) controlPoint2: CGPointMake(671.4, 1024)];
    [bezier4Path addLineToPoint: CGPointMake(382.2, 1024)];
    [bezier4Path addCurveToPoint: CGPointMake(349.8, 996.8) controlPoint1: CGPointMake(366.2, 1024) controlPoint2: CGPointMake(352.6, 1012.6)];
    [bezier4Path addCurveToPoint: CGPointMake(371, 960.2) controlPoint1: CGPointMake(347, 981) controlPoint2: CGPointMake(356, 965.6)];
    [bezier4Path addCurveToPoint: CGPointMake(499.1, 860.4) controlPoint1: CGPointMake(433.4, 937.7) controlPoint2: CGPointMake(475.4, 905)];
    [bezier4Path addLineToPoint: CGPointMake(499.1, 521)];
    [bezier4Path addCurveToPoint: CGPointMake(241.9, 28.3) controlPoint1: CGPointMake(341.7, 501.1) controlPoint2: CGPointMake(255.2, 335.5)];
    [bezier4Path addLineToPoint: CGPointMake(240.7, 0)];
    [bezier4Path addLineToPoint: CGPointMake(786.1, 0)];
    [bezier4Path addLineToPoint: CGPointMake(786.1, 0)];
    [bezier4Path closePath];
    [namedColor setFill];
    [bezier4Path fill];
}

+ (void)drawSpecialsIconWithColorName: (NSString*)colorName;
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();


    //// Variable Declarations
    UIColor* namedColor = [colorName isEqualToString: @"myTintColor"] ? SHStyleKit.myTintColor : [colorName isEqualToString: @"myTintColorTransparent"] ? SHStyleKit.myTintColorTransparent : [colorName isEqualToString: @"myTextColor"] ? SHStyleKit.myTextColor : [colorName isEqualToString: @"myWhiteColor"] ? SHStyleKit.myWhiteColor : SHStyleKit.myTintColor;

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(499.1, 1021.2)];
    [bezierPath addCurveToPoint: CGPointMake(450.1, 991.7) controlPoint1: CGPointMake(478.5, 1021.2) controlPoint2: CGPointMake(459.7, 1009.9)];
    [bezierPath addLineToPoint: CGPointMake(339.5, 782.7)];
    [bezierPath addLineToPoint: CGPointMake(103.4, 768.3)];
    [bezierPath addCurveToPoint: CGPointMake(57.4, 738) controlPoint1: CGPointMake(83.6, 767) controlPoint2: CGPointMake(66.4, 755.7)];
    [bezierPath addCurveToPoint: CGPointMake(60.3, 682.9) controlPoint1: CGPointMake(48.4, 720.2) controlPoint2: CGPointMake(49.5, 699.7)];
    [bezierPath addLineToPoint: CGPointMake(465, 55.2)];
    [bezierPath addCurveToPoint: CGPointMake(515.9, 24.7) controlPoint1: CGPointMake(476.2, 37.8) controlPoint2: CGPointMake(495.3, 26.4)];
    [bezierPath addLineToPoint: CGPointMake(794.2, 2.4)];
    [bezierPath addCurveToPoint: CGPointMake(862.5, 46.5) controlPoint1: CGPointMake(824.3, 0) controlPoint2: CGPointMake(852.4, 18.3)];
    [bezierPath addLineToPoint: CGPointMake(957, 309.3)];
    [bezierPath addCurveToPoint: CGPointMake(950.3, 368.2) controlPoint1: CGPointMake(964, 328.8) controlPoint2: CGPointMake(961.5, 350.8)];
    [bezierPath addLineToPoint: CGPointMake(545.7, 995.8)];
    [bezierPath addCurveToPoint: CGPointMake(499.1, 1021.2) controlPoint1: CGPointMake(535.4, 1011.7) controlPoint2: CGPointMake(518, 1021.2)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(799.6, 49.1)];
    [bezierPath addCurveToPoint: CGPointMake(798, 49.2) controlPoint1: CGPointMake(799.1, 49.1) controlPoint2: CGPointMake(798.5, 49.1)];
    [bezierPath addLineToPoint: CGPointMake(519.6, 71.5)];
    [bezierPath addCurveToPoint: CGPointMake(504.3, 80.6) controlPoint1: CGPointMake(513.4, 72) controlPoint2: CGPointMake(507.7, 75.4)];
    [bezierPath addLineToPoint: CGPointMake(99.7, 708.3)];
    [bezierPath addCurveToPoint: CGPointMake(99.3, 716.8) controlPoint1: CGPointMake(97.4, 711.9) controlPoint2: CGPointMake(98.4, 715.2)];
    [bezierPath addCurveToPoint: CGPointMake(106.4, 721.5) controlPoint1: CGPointMake(100.1, 718.4) controlPoint2: CGPointMake(102.1, 721.2)];
    [bezierPath addLineToPoint: CGPointMake(368.7, 737.5)];
    [bezierPath addLineToPoint: CGPointMake(491.6, 969.8)];
    [bezierPath addCurveToPoint: CGPointMake(499.2, 974.3) controlPoint1: CGPointMake(493.8, 973.9) controlPoint2: CGPointMake(497.6, 974.3)];
    [bezierPath addCurveToPoint: CGPointMake(506.4, 970.4) controlPoint1: CGPointMake(500.9, 974.3) controlPoint2: CGPointMake(504.2, 973.8)];
    [bezierPath addLineToPoint: CGPointMake(911, 342.8)];
    [bezierPath addCurveToPoint: CGPointMake(913, 325.1) controlPoint1: CGPointMake(914.4, 337.6) controlPoint2: CGPointMake(915.1, 331)];
    [bezierPath addLineToPoint: CGPointMake(818.5, 62.3)];
    [bezierPath addCurveToPoint: CGPointMake(799.6, 49.1) controlPoint1: CGPointMake(815.6, 54.4) controlPoint2: CGPointMake(808, 49.1)];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;

    [namedColor setFill];
    [bezierPath fill];


    //// Bezier 2 Drawing
    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(714.7, 254.6)];
    [bezier2Path addCurveToPoint: CGPointMake(685.5, 246) controlPoint1: CGPointMake(704.3, 254.6) controlPoint2: CGPointMake(694.2, 251.6)];
    [bezier2Path addCurveToPoint: CGPointMake(662, 212.1) controlPoint1: CGPointMake(673.4, 238.2) controlPoint2: CGPointMake(665, 226.1)];
    [bezier2Path addCurveToPoint: CGPointMake(669.4, 171.5) controlPoint1: CGPointMake(659, 198) controlPoint2: CGPointMake(661.6, 183.6)];
    [bezier2Path addCurveToPoint: CGPointMake(714.8, 146.8) controlPoint1: CGPointMake(679.4, 156) controlPoint2: CGPointMake(696.3, 146.8)];
    [bezier2Path addCurveToPoint: CGPointMake(744, 155.4) controlPoint1: CGPointMake(725.2, 146.8) controlPoint2: CGPointMake(735.3, 149.8)];
    [bezier2Path addCurveToPoint: CGPointMake(760.1, 230) controlPoint1: CGPointMake(769, 171.5) controlPoint2: CGPointMake(776.2, 205)];
    [bezier2Path addCurveToPoint: CGPointMake(714.7, 254.6) controlPoint1: CGPointMake(750.1, 245.4) controlPoint2: CGPointMake(733.2, 254.6)];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(714.8, 170.1)];
    [bezier2Path addCurveToPoint: CGPointMake(689.1, 184.1) controlPoint1: CGPointMake(704.4, 170.1) controlPoint2: CGPointMake(694.8, 175.3)];
    [bezier2Path addCurveToPoint: CGPointMake(684.9, 207.1) controlPoint1: CGPointMake(684.7, 191) controlPoint2: CGPointMake(683.2, 199.1)];
    [bezier2Path addCurveToPoint: CGPointMake(698.2, 226.3) controlPoint1: CGPointMake(686.6, 215.1) controlPoint2: CGPointMake(691.3, 221.9)];
    [bezier2Path addCurveToPoint: CGPointMake(740.4, 217.2) controlPoint1: CGPointMake(712, 235.2) controlPoint2: CGPointMake(731.6, 230.8)];
    [bezier2Path addCurveToPoint: CGPointMake(731.3, 175) controlPoint1: CGPointMake(749.5, 203.1) controlPoint2: CGPointMake(745.4, 184.1)];
    [bezier2Path addCurveToPoint: CGPointMake(714.8, 170.1) controlPoint1: CGPointMake(726.4, 171.8) controlPoint2: CGPointMake(720.7, 170.1)];
    [bezier2Path closePath];
    bezier2Path.miterLimit = 4;

    [namedColor setFill];
    [bezier2Path fill];


    //// Rectangle Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 515.98, 480.88);
    CGContextRotateCTM(context, 35.99 * M_PI / 180);

    CGRect rectangleRect = CGRectMake(-117.02, -189.62, 234.04, 379.25);
    NSMutableParagraphStyle* rectangleStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
    rectangleStyle.alignment = NSTextAlignmentLeft;

    NSDictionary* rectangleFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"MyriadPro-Bold" size: 408.65], NSForegroundColorAttributeName: namedColor, NSParagraphStyleAttributeName: rectangleStyle};

    [@"$" drawInRect: rectangleRect withAttributes: rectangleFontAttributes];

    CGContextRestoreGState(context);
}

+ (void)drawSpotIconWithColorName: (NSString*)colorName;
{

    //// Variable Declarations
    UIColor* namedColor = [colorName isEqualToString: @"myTintColor"] ? SHStyleKit.myTintColor : [colorName isEqualToString: @"myTintColorTransparent"] ? SHStyleKit.myTintColorTransparent : [colorName isEqualToString: @"myTextColor"] ? SHStyleKit.myTextColor : [colorName isEqualToString: @"myWhiteColor"] ? SHStyleKit.myWhiteColor : SHStyleKit.myTintColor;

    //// Bezier 2 Drawing
    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(510.2, 1024.1)];
    [bezier2Path addLineToPoint: CGPointMake(239.5, 492.3)];
    [bezier2Path addCurveToPoint: CGPointMake(190.4, 321.7) controlPoint1: CGPointMake(207.4, 441.2) controlPoint2: CGPointMake(190.4, 382.2)];
    [bezier2Path addCurveToPoint: CGPointMake(511.5, 0.6) controlPoint1: CGPointMake(190.4, 144.6) controlPoint2: CGPointMake(334.5, 0.6)];
    [bezier2Path addCurveToPoint: CGPointMake(832.6, 321.7) controlPoint1: CGPointMake(688.5, 0.6) controlPoint2: CGPointMake(832.6, 144.7)];
    [bezier2Path addCurveToPoint: CGPointMake(783.7, 492) controlPoint1: CGPointMake(832.6, 382.1) controlPoint2: CGPointMake(815.7, 441)];
    [bezier2Path addLineToPoint: CGPointMake(510.2, 1024.1)];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(511.5, 47.3)];
    [bezier2Path addCurveToPoint: CGPointMake(237.1, 321.7) controlPoint1: CGPointMake(360.2, 47.3) controlPoint2: CGPointMake(237.1, 170.4)];
    [bezier2Path addCurveToPoint: CGPointMake(279.6, 468.2) controlPoint1: CGPointMake(237.1, 373.7) controlPoint2: CGPointMake(251.8, 424.4)];
    [bezier2Path addLineToPoint: CGPointMake(280.7, 470.1)];
    [bezier2Path addLineToPoint: CGPointMake(510.5, 921.4)];
    [bezier2Path addLineToPoint: CGPointMake(743.6, 467.9)];
    [bezier2Path addCurveToPoint: CGPointMake(785.9, 321.7) controlPoint1: CGPointMake(771.3, 424.1) controlPoint2: CGPointMake(785.9, 373.5)];
    [bezier2Path addCurveToPoint: CGPointMake(511.5, 47.3) controlPoint1: CGPointMake(785.8, 170.4) controlPoint2: CGPointMake(662.8, 47.3)];
    [bezier2Path closePath];
    bezier2Path.miterLimit = 4;

    [namedColor setFill];
    [bezier2Path fill];


    //// Bezier 4 Drawing
    UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
    [bezier4Path moveToPoint: CGPointMake(516.5, 459.7)];
    [bezier4Path addCurveToPoint: CGPointMake(402.6, 345.8) controlPoint1: CGPointMake(453.7, 459.7) controlPoint2: CGPointMake(402.6, 408.6)];
    [bezier4Path addCurveToPoint: CGPointMake(516.5, 231.8) controlPoint1: CGPointMake(402.6, 283) controlPoint2: CGPointMake(453.7, 231.8)];
    [bezier4Path addCurveToPoint: CGPointMake(630.4, 345.8) controlPoint1: CGPointMake(579.3, 231.8) controlPoint2: CGPointMake(630.4, 282.9)];
    [bezier4Path addCurveToPoint: CGPointMake(516.5, 459.7) controlPoint1: CGPointMake(630.4, 408.7) controlPoint2: CGPointMake(579.3, 459.7)];
    [bezier4Path closePath];
    [bezier4Path moveToPoint: CGPointMake(516.5, 266.8)];
    [bezier4Path addCurveToPoint: CGPointMake(437.6, 345.7) controlPoint1: CGPointMake(473, 266.8) controlPoint2: CGPointMake(437.6, 302.2)];
    [bezier4Path addCurveToPoint: CGPointMake(516.5, 424.6) controlPoint1: CGPointMake(437.6, 389.2) controlPoint2: CGPointMake(473, 424.6)];
    [bezier4Path addCurveToPoint: CGPointMake(595.4, 345.7) controlPoint1: CGPointMake(560, 424.6) controlPoint2: CGPointMake(595.4, 389.2)];
    [bezier4Path addCurveToPoint: CGPointMake(516.5, 266.8) controlPoint1: CGPointMake(595.4, 302.2) controlPoint2: CGPointMake(560, 266.8)];
    [bezier4Path closePath];
    bezier4Path.miterLimit = 4;

    [namedColor setFill];
    [bezier4Path fill];
}

+ (void)drawCocktailIconWithColorName: (NSString*)colorName;
{

    //// Variable Declarations
    UIColor* namedColor = [colorName isEqualToString: @"myTintColor"] ? SHStyleKit.myTintColor : [colorName isEqualToString: @"myTintColorTransparent"] ? SHStyleKit.myTintColorTransparent : [colorName isEqualToString: @"myTextColor"] ? SHStyleKit.myTextColor : [colorName isEqualToString: @"myWhiteColor"] ? SHStyleKit.myWhiteColor : SHStyleKit.myTintColor;

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(548.5, 589.5)];
    [bezierPath addLineToPoint: CGPointMake(919, 202.8)];
    [bezierPath addLineToPoint: CGPointMake(716.2, 202.8)];
    [bezierPath addLineToPoint: CGPointMake(769.6, 147.1)];
    [bezierPath addCurveToPoint: CGPointMake(821.8, 132.3) controlPoint1: CGPointMake(786.6, 152) controlPoint2: CGPointMake(807, 147)];
    [bezierPath addCurveToPoint: CGPointMake(836.1, 77.6) controlPoint1: CGPointMake(837.2, 116.8) controlPoint2: CGPointMake(842.2, 95.2)];
    [bezierPath addLineToPoint: CGPointMake(889.3, 22)];
    [bezierPath addLineToPoint: CGPointMake(866.1, 0)];
    [bezierPath addLineToPoint: CGPointMake(814.6, 53.8)];
    [bezierPath addCurveToPoint: CGPointMake(755.5, 65.9) controlPoint1: CGPointMake(796.4, 44.9) controlPoint2: CGPointMake(772.4, 49)];
    [bezierPath addCurveToPoint: CGPointMake(744.3, 127.2) controlPoint1: CGPointMake(738, 83.5) controlPoint2: CGPointMake(734.1, 108.8)];
    [bezierPath addLineToPoint: CGPointMake(672, 202.8)];
    [bezierPath addLineToPoint: CGPointMake(130, 202.8)];
    [bezierPath addLineToPoint: CGPointMake(500.6, 589.5)];
    [bezierPath addLineToPoint: CGPointMake(500.6, 915.2)];
    [bezierPath addLineToPoint: CGPointMake(321.6, 992.9)];
    [bezierPath addCurveToPoint: CGPointMake(727.6, 992.9) controlPoint1: CGPointMake(321.6, 992.9) controlPoint2: CGPointMake(523.5, 1064.8)];
    [bezierPath addLineToPoint: CGPointMake(548.6, 915.2)];
    [bezierPath addLineToPoint: CGPointMake(548.6, 589.5)];
    [bezierPath addLineToPoint: CGPointMake(548.5, 589.5)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(578.1, 300.7)];
    [bezierPath addLineToPoint: CGPointMake(498.8, 383.6)];
    [bezierPath addLineToPoint: CGPointMake(521.8, 405.7)];
    [bezierPath addLineToPoint: CGPointMake(622.4, 300.8)];
    [bezierPath addLineToPoint: CGPointMake(764.1, 300.8)];
    [bezierPath addLineToPoint: CGPointMake(524.6, 550.6)];
    [bezierPath addLineToPoint: CGPointMake(285.1, 300.7)];
    [bezierPath addLineToPoint: CGPointMake(578.1, 300.7)];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;

    [namedColor setFill];
    [bezierPath fill];
}

+ (void)drawBeerIconWithColorName: (NSString*)colorName;
{

    //// Variable Declarations
    UIColor* namedColor = [colorName isEqualToString: @"myTintColor"] ? SHStyleKit.myTintColor : [colorName isEqualToString: @"myTintColorTransparent"] ? SHStyleKit.myTintColorTransparent : [colorName isEqualToString: @"myTextColor"] ? SHStyleKit.myTextColor : [colorName isEqualToString: @"myWhiteColor"] ? SHStyleKit.myWhiteColor : SHStyleKit.myTintColor;

    //// Bezier 4 Drawing
    UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
    [bezier4Path moveToPoint: CGPointMake(579.72, 716.18)];
    [bezier4Path addCurveToPoint: CGPointMake(579.72, 736.82) controlPoint1: CGPointMake(585.43, 721.88) controlPoint2: CGPointMake(585.43, 731.12)];
    [bezier4Path addCurveToPoint: CGPointMake(559.08, 736.82) controlPoint1: CGPointMake(574.02, 742.53) controlPoint2: CGPointMake(564.78, 742.53)];
    [bezier4Path addCurveToPoint: CGPointMake(559.08, 716.18) controlPoint1: CGPointMake(553.37, 731.12) controlPoint2: CGPointMake(553.37, 721.88)];
    [bezier4Path addCurveToPoint: CGPointMake(579.72, 716.18) controlPoint1: CGPointMake(564.78, 710.47) controlPoint2: CGPointMake(574.02, 710.47)];
    [bezier4Path closePath];
    bezier4Path.miterLimit = 4;

    [namedColor setFill];
    [bezier4Path fill];


    //// Bezier 5 Drawing
    UIBezierPath* bezier5Path = UIBezierPath.bezierPath;
    [bezier5Path moveToPoint: CGPointMake(620.13, 569.67)];
    [bezier5Path addCurveToPoint: CGPointMake(620.13, 589.33) controlPoint1: CGPointMake(625.56, 575.1) controlPoint2: CGPointMake(625.56, 583.9)];
    [bezier5Path addCurveToPoint: CGPointMake(600.47, 589.33) controlPoint1: CGPointMake(614.7, 594.76) controlPoint2: CGPointMake(605.9, 594.76)];
    [bezier5Path addCurveToPoint: CGPointMake(600.47, 569.67) controlPoint1: CGPointMake(595.04, 583.9) controlPoint2: CGPointMake(595.04, 575.1)];
    [bezier5Path addCurveToPoint: CGPointMake(620.13, 569.67) controlPoint1: CGPointMake(605.9, 564.24) controlPoint2: CGPointMake(614.7, 564.24)];
    [bezier5Path closePath];
    bezier5Path.miterLimit = 4;

    [namedColor setFill];
    [bezier5Path fill];


    //// Bezier 6 Drawing
    UIBezierPath* bezier6Path = UIBezierPath.bezierPath;
    [bezier6Path moveToPoint: CGPointMake(557.9, 448.5)];
    [bezier6Path addCurveToPoint: CGPointMake(557.9, 464.9) controlPoint1: CGPointMake(562.43, 453.03) controlPoint2: CGPointMake(562.43, 460.37)];
    [bezier6Path addCurveToPoint: CGPointMake(541.5, 464.9) controlPoint1: CGPointMake(553.37, 469.43) controlPoint2: CGPointMake(546.03, 469.43)];
    [bezier6Path addCurveToPoint: CGPointMake(541.5, 448.5) controlPoint1: CGPointMake(536.97, 460.37) controlPoint2: CGPointMake(536.97, 453.03)];
    [bezier6Path addCurveToPoint: CGPointMake(557.9, 448.5) controlPoint1: CGPointMake(546.03, 443.97) controlPoint2: CGPointMake(553.37, 443.97)];
    [bezier6Path closePath];
    bezier6Path.miterLimit = 4;

    [namedColor setFill];
    [bezier6Path fill];


    //// Bezier 7 Drawing
    UIBezierPath* bezier7Path = UIBezierPath.bezierPath;
    [bezier7Path moveToPoint: CGPointMake(611.61, 280.09)];
    [bezier7Path addCurveToPoint: CGPointMake(611.61, 309.51) controlPoint1: CGPointMake(619.73, 288.22) controlPoint2: CGPointMake(619.73, 301.38)];
    [bezier7Path addCurveToPoint: CGPointMake(582.19, 309.51) controlPoint1: CGPointMake(603.48, 317.63) controlPoint2: CGPointMake(590.32, 317.63)];
    [bezier7Path addCurveToPoint: CGPointMake(582.19, 280.09) controlPoint1: CGPointMake(574.07, 301.38) controlPoint2: CGPointMake(574.07, 288.22)];
    [bezier7Path addCurveToPoint: CGPointMake(611.61, 280.09) controlPoint1: CGPointMake(590.32, 271.97) controlPoint2: CGPointMake(603.48, 271.97)];
    [bezier7Path closePath];
    bezier7Path.miterLimit = 4;

    [namedColor setFill];
    [bezier7Path fill];


    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(726.1, 42.4)];
    [bezierPath addLineToPoint: CGPointMake(302.5, 42.4)];
    [bezierPath addCurveToPoint: CGPointMake(275.82, 145.98) controlPoint1: CGPointMake(289.81, 80.68) controlPoint2: CGPointMake(281.17, 114.87)];
    [bezierPath addCurveToPoint: CGPointMake(745.29, 142.58) controlPoint1: CGPointMake(351.27, 145.43) controlPoint2: CGPointMake(655.71, 143.23)];
    [bezierPath addCurveToPoint: CGPointMake(726.1, 42.4) controlPoint1: CGPointMake(741.74, 112.36) controlPoint2: CGPointMake(735.54, 79.25)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(748.67, 184.96)];
    [bezierPath addCurveToPoint: CGPointMake(270.36, 188.42) controlPoint1: CGPointMake(660.92, 185.59) controlPoint2: CGPointMake(335.41, 187.95)];
    [bezierPath addCurveToPoint: CGPointMake(322.2, 433.9) controlPoint1: CGPointMake(262.1, 287.56) controlPoint2: CGPointMake(289.8, 355.05)];
    [bezierPath addCurveToPoint: CGPointMake(374.6, 978.1) controlPoint1: CGPointMake(371.5, 554.1) controlPoint2: CGPointMake(427.3, 689.8)];
    [bezierPath addLineToPoint: CGPointMake(660.5, 978.1)];
    [bezierPath addCurveToPoint: CGPointMake(700.1, 421.6) controlPoint1: CGPointMake(603.9, 678) controlPoint2: CGPointMake(655, 542)];
    [bezierPath addCurveToPoint: CGPointMake(748.67, 184.96) controlPoint1: CGPointMake(727.62, 348.31) controlPoint2: CGPointMake(752.58, 281.81)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(758.7, 0)];
    [bezierPath addCurveToPoint: CGPointMake(763, 15.6) controlPoint1: CGPointMake(758.7, 0) controlPoint2: CGPointMake(763, 15.6)];
    [bezierPath addCurveToPoint: CGPointMake(739.9, 436.5) controlPoint1: CGPointMake(819.8, 223.5) controlPoint2: CGPointMake(781, 327)];
    [bezierPath addCurveToPoint: CGPointMake(707.1, 995.1) controlPoint1: CGPointMake(695.5, 554.9) controlPoint2: CGPointMake(645.1, 689.1)];
    [bezierPath addLineToPoint: CGPointMake(712.2, 1020.5)];
    [bezierPath addLineToPoint: CGPointMake(323.2, 1020.5)];
    [bezierPath addLineToPoint: CGPointMake(328.3, 995.2)];
    [bezierPath addCurveToPoint: CGPointMake(283, 450) controlPoint1: CGPointMake(386.5, 702) controlPoint2: CGPointMake(331.5, 568.1)];
    [bezierPath addCurveToPoint: CGPointMake(267.3, 14.2) controlPoint1: CGPointMake(236.4, 336.5) controlPoint2: CGPointMake(192.4, 229.4)];
    [bezierPath addLineToPoint: CGPointMake(272.3, 0)];
    [bezierPath addLineToPoint: CGPointMake(758.7, 0)];
    [bezierPath addLineToPoint: CGPointMake(758.7, 0)];
    [bezierPath closePath];
    [namedColor setFill];
    [bezierPath fill];
}

+ (void)drawNavigationArrowIconWithColorName: (NSString*)colorName;
{

    //// Variable Declarations
    UIColor* namedColor = [colorName isEqualToString: @"myTintColor"] ? SHStyleKit.myTintColor : [colorName isEqualToString: @"myTintColorTransparent"] ? SHStyleKit.myTintColorTransparent : [colorName isEqualToString: @"myTextColor"] ? SHStyleKit.myTextColor : [colorName isEqualToString: @"myWhiteColor"] ? SHStyleKit.myWhiteColor : SHStyleKit.myTintColor;

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(317.5, 2.8)];
    [bezierPath addLineToPoint: CGPointMake(289.9, 25.6)];
    [bezierPath addLineToPoint: CGPointMake(691.7, 512)];
    [bezierPath addLineToPoint: CGPointMake(289.9, 998.4)];
    [bezierPath addLineToPoint: CGPointMake(317.5, 1021.2)];
    [bezierPath addLineToPoint: CGPointMake(738.1, 512)];
    [bezierPath addLineToPoint: CGPointMake(317.5, 2.8)];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;

    [namedColor setFill];
    [bezierPath fill];
}

+ (void)drawDirectionArrowIconWithColorName: (NSString*)colorName;
{

    //// Variable Declarations
    UIColor* namedColor = [colorName isEqualToString: @"myTintColor"] ? SHStyleKit.myTintColor : [colorName isEqualToString: @"myTintColorTransparent"] ? SHStyleKit.myTintColorTransparent : [colorName isEqualToString: @"myTextColor"] ? SHStyleKit.myTextColor : [colorName isEqualToString: @"myWhiteColor"] ? SHStyleKit.myWhiteColor : SHStyleKit.myTintColor;

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(1018.8, 502.9)];
    [bezierPath addCurveToPoint: CGPointMake(1018.3, 497.5) controlPoint1: CGPointMake(1018.6, 501.1) controlPoint2: CGPointMake(1018.6, 499.3)];
    [bezierPath addCurveToPoint: CGPointMake(996.5, 458.7) controlPoint1: CGPointMake(1015.4, 482.2) controlPoint2: CGPointMake(1007.5, 468.8)];
    [bezierPath addLineToPoint: CGPointMake(624.9, 86.4)];
    [bezierPath addCurveToPoint: CGPointMake(524.8, 86.3) controlPoint1: CGPointMake(597.3, 58.7) controlPoint2: CGPointMake(552.4, 58.7)];
    [bezierPath addLineToPoint: CGPointMake(523.8, 87.3)];
    [bezierPath addCurveToPoint: CGPointMake(523.7, 187.4) controlPoint1: CGPointMake(496.1, 114.9) controlPoint2: CGPointMake(496.1, 159.8)];
    [bezierPath addLineToPoint: CGPointMake(775.7, 439.9)];
    [bezierPath addLineToPoint: CGPointMake(73.2, 439.9)];
    [bezierPath addCurveToPoint: CGPointMake(2.4, 510.7) controlPoint1: CGPointMake(34.1, 439.9) controlPoint2: CGPointMake(2.4, 471.6)];
    [bezierPath addLineToPoint: CGPointMake(2.4, 512.1)];
    [bezierPath addCurveToPoint: CGPointMake(73.2, 582.9) controlPoint1: CGPointMake(2.4, 551.2) controlPoint2: CGPointMake(34.1, 582.9)];
    [bezierPath addLineToPoint: CGPointMake(775.7, 582.9)];
    [bezierPath addLineToPoint: CGPointMake(523.7, 835.4)];
    [bezierPath addCurveToPoint: CGPointMake(523.8, 935.5) controlPoint1: CGPointMake(496.1, 863.1) controlPoint2: CGPointMake(496.1, 907.9)];
    [bezierPath addLineToPoint: CGPointMake(524.8, 936.5)];
    [bezierPath addCurveToPoint: CGPointMake(624.9, 936.4) controlPoint1: CGPointMake(552.5, 964.1) controlPoint2: CGPointMake(597.3, 964.1)];
    [bezierPath addLineToPoint: CGPointMake(996.5, 564.1)];
    [bezierPath addCurveToPoint: CGPointMake(1018.3, 525.3) controlPoint1: CGPointMake(1007.5, 554) controlPoint2: CGPointMake(1015.4, 540.6)];
    [bezierPath addCurveToPoint: CGPointMake(1018.8, 519.9) controlPoint1: CGPointMake(1018.6, 523.5) controlPoint2: CGPointMake(1018.6, 521.7)];
    [bezierPath addCurveToPoint: CGPointMake(1019.6, 512.1) controlPoint1: CGPointMake(1019.1, 517.3) controlPoint2: CGPointMake(1019.6, 514.8)];
    [bezierPath addLineToPoint: CGPointMake(1019.6, 510.7)];
    [bezierPath addCurveToPoint: CGPointMake(1018.8, 502.9) controlPoint1: CGPointMake(1019.6, 508) controlPoint2: CGPointMake(1019.1, 505.5)];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;

    [namedColor setFill];
    [bezierPath fill];
}

+ (void)drawSearchIconWithColorName: (NSString*)colorName;
{

    //// Variable Declarations
    UIColor* namedColor = [colorName isEqualToString: @"myTintColor"] ? SHStyleKit.myTintColor : [colorName isEqualToString: @"myTintColorTransparent"] ? SHStyleKit.myTintColorTransparent : [colorName isEqualToString: @"myTextColor"] ? SHStyleKit.myTextColor : [colorName isEqualToString: @"myWhiteColor"] ? SHStyleKit.myWhiteColor : SHStyleKit.myTintColor;

    //// Bezier 3 Drawing
    UIBezierPath* bezier3Path = UIBezierPath.bezierPath;
    [bezier3Path moveToPoint: CGPointMake(430.2, 50.1)];
    [bezier3Path addCurveToPoint: CGPointMake(81, 399.3) controlPoint1: CGPointMake(237.6, 50.1) controlPoint2: CGPointMake(81, 206.8)];
    [bezier3Path addCurveToPoint: CGPointMake(430.2, 748.5) controlPoint1: CGPointMake(81, 591.8) controlPoint2: CGPointMake(237.6, 748.5)];
    [bezier3Path addCurveToPoint: CGPointMake(779.4, 399.3) controlPoint1: CGPointMake(622.8, 748.5) controlPoint2: CGPointMake(779.4, 591.9)];
    [bezier3Path addCurveToPoint: CGPointMake(430.2, 50.1) controlPoint1: CGPointMake(779.4, 206.7) controlPoint2: CGPointMake(622.7, 50.1)];
    [bezier3Path closePath];
    [bezier3Path moveToPoint: CGPointMake(824.5, 399.4)];
    [bezier3Path addCurveToPoint: CGPointMake(751.91, 627.1) controlPoint1: CGPointMake(824.5, 484.16) controlPoint2: CGPointMake(797.61, 562.75)];
    [bezier3Path addCurveToPoint: CGPointMake(1015.8, 916.7) controlPoint1: CGPointMake(799.34, 679.14) controlPoint2: CGPointMake(1015.8, 916.7)];
    [bezier3Path addLineToPoint: CGPointMake(899.2, 1023)];
    [bezier3Path addCurveToPoint: CGPointMake(636.81, 735.04) controlPoint1: CGPointMake(899.2, 1023) controlPoint2: CGPointMake(687.11, 790.25)];
    [bezier3Path addCurveToPoint: CGPointMake(430.2, 793.6) controlPoint1: CGPointMake(576.69, 772.16) controlPoint2: CGPointMake(505.9, 793.6)];
    [bezier3Path addCurveToPoint: CGPointMake(35.9, 399.3) controlPoint1: CGPointMake(212.8, 793.6) controlPoint2: CGPointMake(35.9, 616.7)];
    [bezier3Path addCurveToPoint: CGPointMake(430.2, 5.1) controlPoint1: CGPointMake(35.9, 181.9) controlPoint2: CGPointMake(212.8, 5.1)];
    [bezier3Path addCurveToPoint: CGPointMake(824.5, 399.4) controlPoint1: CGPointMake(647.6, 5.1) controlPoint2: CGPointMake(824.5, 182)];
    [bezier3Path closePath];
    [namedColor setFill];
    [bezier3Path fill];
}

+ (void)drawGradientBackgroundWithWidth: (CGFloat)width height: (CGFloat)height;
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* myTintColorGradientColor1 = [UIColor colorWithRed: 0.918 green: 0.682 blue: 0.455 alpha: 1];
    UIColor* myTintColorGradientColor2 = [UIColor colorWithRed: 0.933 green: 0.627 blue: 0.518 alpha: 1];

    //// Gradient Declarations
    CGFloat myTintColorGradientLocations[] = {0, 1};
    CGGradientRef myTintColorGradient = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)myTintColorGradientColor1.CGColor, (id)myTintColorGradientColor2.CGColor], myTintColorGradientLocations);

    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(0, 0, width, height)];
    CGContextSaveGState(context);
    [rectanglePath addClip];
    CGContextDrawLinearGradient(context, myTintColorGradient, CGPointMake(160, -0), CGPointMake(160, 568), 0);
    CGContextRestoreGState(context);


    //// Cleanup
    CGGradientRelease(myTintColorGradient);
    CGColorSpaceRelease(colorSpace);
}

@end
