//
//  SHStyleKit.h
//  SpotHopper
//
//  Created by SpotHopper on 5/14/14.
//  Copyright (c) 2014 SpotHopper. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface SHStyleKit : NSObject

// Colors
+ (UIColor*)myTintColor;
+ (UIColor*)myTintColorTransparent;
+ (UIColor*)myTextColor;
+ (UIColor*)myWhiteColor;
+ (UIColor*)myLightHeaderColor;

// Drawing Methods
+ (void)drawWineIconWithColorName: (NSString*)colorName;
+ (void)drawSpecialsIconWithColorName: (NSString*)colorName;
+ (void)drawSpotIconWithColorName: (NSString*)colorName;
+ (void)drawCocktailIconWithColorName: (NSString*)colorName;
+ (void)drawBeerIconWithColorName: (NSString*)colorName;
+ (void)drawNavigationArrowIconWithColorName: (NSString*)colorName;
+ (void)drawDirectionArrowIconWithColorName: (NSString*)colorName;
+ (void)drawSearchIconWithColorName: (NSString*)colorName;
+ (void)drawGradientBackgroundWithWidth: (CGFloat)width height: (CGFloat)height;

@end
